/* Original bounded file inspection and PS1 VAB decoding.
 * VAB structure cross-checked with VGMTrans's Vab.cpp and psx-spx.
 * A VAB bank is NOT a music sequence; it never generates invented notes.
 */
(function(scope){'use strict';
const LIMIT={input:32*1024*1024,inflated:32*1024*1024,seconds:180,output:128*1024*1024,files:40,samples:255};
const str=(b,p,n)=>new TextDecoder('utf-8',{fatal:false}).decode(b.subarray(p,p+n)).replace(/\0.*$/s,'').trim();
function bytes(data){return data instanceof Uint8Array?data:new Uint8Array(data);}
function crc32(data){let c=0xffffffff;for(const b of data){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function magic(b,s,p=0){return b.length>=p+s.length&&[...s].every((c,i)=>b[p+i]===c.charCodeAt(0));}
async function inflate(data,format='gzip'){if(typeof DecompressionStream==='undefined')throw Error('이 브라우저에 압축 해제 기능이 없습니다. 압축을 푼 VGM 파일로 다시 선택하세요.');const reader=new Blob([data]).stream().pipeThrough(new DecompressionStream(format)).getReader();const parts=[];let n=0;try{while(true){const r=await reader.read();if(r.done)break;n+=r.value.length;if(n>LIMIT.inflated){await reader.cancel();throw Error('압축 해제 후 32MiB 제한을 넘습니다.');}parts.push(r.value);}}finally{reader.releaseLock();}const out=new Uint8Array(n);let at=0;for(const p of parts){out.set(p,at);at+=p.length;}return out;}
function safePath(name){const p=String(name).replace(/\\/g,'/');if(!p||p.startsWith('/')||/^[a-z]:/i.test(p)||p.split('/').some(x=>x==='..'||x==='.'||!x)||/[\x00-\x1f]/.test(p))throw Error('안전하지 않은 동반 파일 경로: '+name);return p;}
function psf(b,name){if(b.length<16)throw Error('잘린 PSF 계열 헤더입니다.');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),type=b[3],reserve=v.getUint32(4,true),compressed=v.getUint32(8,true),end=16+reserve+compressed;if(end>b.length||end>LIMIT.input)throw Error('PSF 블록 길이가 파일을 벗어납니다.');if(crc32(b.subarray(16+reserve,end))!==v.getUint32(12,true))throw Error('PSF 압축 블록 CRC32가 맞지 않습니다.');const tags={};if(magic(b,'[TAG]',end)){for(const line of str(b,end+5,b.length-end-5).split(/\r?\n/)){const i=line.indexOf('=');if(i>0){const key=line.slice(0,i).trim().toLowerCase();if(key.length<80)tags[key]=line.slice(i+1).trim().slice(0,2048);}}}const dependencies=Object.keys(tags).filter(k=>/^_lib(?:\d+)?$/.test(k)).map(k=>safePath(tags[k]));const format=({1:'PSF',2:'PSF2',0x22:'GSF',0x24:'2SF',0x25:'NCSF'})[type]||'PSF-'+type.toString(16);return{format,kind:'container',name,title:tags.title||name,tags,dependencies,ready:false,reason:format+'는 동반 파일 검사까지이며 이 버전에는 실행·채널 추출 엔진이 아직 연결되지 않았습니다. 빈 트랙을 만들지 않습니다.'};}
function vgmCheck(b){if(b.length<64)throw Error('잘린 VGM 헤더입니다.');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),version=v.getUint32(8,true),end=v.getUint32(4,true)+4,start=version>=0x150?(v.getUint32(0x34,true)?v.getUint32(0x34,true)+0x34:64):64;if(start<64||start>b.length||end>b.length||end<start)throw Error('VGM 데이터 위치/길이가 잘못됐습니다.');const unsupported=[[0x10,'YM2413'],[0x30,'YM2151'],[0x38,'Sega PCM'],[0x40,'RF5C68'],[0x44,'YM2203'],[0x48,'YM2608'],[0x4c,'YM2610'],[0x50,'YM3812'],[0x54,'YM3526'],[0x58,'Y8950'],[0x5c,'YMF262'],[0x60,'YMF278B'],[0x64,'YMF271'],[0x68,'YMZ280B'],[0x6c,'RF5C164'],[0x70,'PWM'],[0x74,'AY8910'],[0x80,'Game Boy'],[0x84,'NES'],[0x88,'MultiPCM'],[0x8c,'uPD7759'],[0x90,'OKIM6258'],[0x94,'OKIM6295'],[0x98,'K051649'],[0x9c,'K054539'],[0xa0,'HuC6280'],[0xa4,'C140'],[0xa8,'K053260'],[0xac,'Pokey'],[0xb0,'QSound'],[0xb8,'SCSP'],[0xc0,'WonderSwan'],[0xc4,'VSU'],[0xc8,'SAA1099'],[0xcc,'ES5503'],[0xd0,'ES5506'],[0xd8,'X1-010'],[0xdc,'C352'],[0xe0,'GA20']];for(const [off,chip]of unsupported)if(off+4<=start&&off+4<=b.length&&v.getUint32(off,true))throw Error('이 VGM은 '+chip+' 칩을 사용합니다. 이번 채널 엔진은 SN76489·YM2612 VGM만 지원하며 다른 칩을 무시해 부분 변환하지 않습니다.');for(const off of [0xc,0x10,0x2c])if(off+4<=start&&(v.getUint32(off,true)&0x40000000))throw Error('이중 칩 VGM은 아직 지원하지 않습니다.');let p=start,commands=0,stopped=false;while(p<end){if(++commands>2000000)throw Error('VGM 명령 수 제한');const c=b[p++];if(c===0x66){stopped=true;break;}let n=0;if(c===0x4f||c===0x50)n=1;else if(c>=0x52&&c<=0x53)n=2;else if(c===0x61)n=2;else if(c===0x62||c===0x63||(c>=0x70&&c<=0x8f))n=0;else if(c===0xe0)n=4;else if(c===0x67){if(p+6>end||b[p]!==0x66)throw Error('잘린 VGM 데이터 블록');const type=b[p+1],size=v.getUint32(p+2,true)&0x7fffffff;if(type!==0)throw Error('아직 지원하지 않는 VGM 데이터 블록 종류: '+type);n=6+size;}else throw Error('지원하지 않는 VGM 명령 0x'+c.toString(16)+' · 부분 가져오기는 하지 않습니다.');if(p+n>end)throw Error('잘린 VGM 명령');p+=n;}if(!stopped)throw Error('VGM 종료 명령이 없습니다.');return {vgmVersion:version,commands};}
async function inspect(data,name='music'){let b=bytes(data);if(!b.length||b.length>LIMIT.input)throw Error('게임 음악은 32MiB 이하 파일을 선택하세요.');let compressed=false;if(b[0]===0x1f&&b[1]===0x8b){b=await inflate(b);compressed=true;}let format,title=name,extra={};if(magic(b,'NESM\x1a')){if(b.length<128)throw Error('잘린 NSF');format='NSF';title=str(b,14,32)||name;extra={songs:b[6],defaultSong:Math.max(0,b[7]-1),expansion:b[123]};if(b[5]!==1)throw Error('이번 NSF 엔진은 NSF v1 헤더를 지원합니다.');if(!b[6])throw Error('NSF에 곡 수가 없습니다.');}
 else if(magic(b,'NSFE'))format='NSFE';else if(magic(b,'GBS')){if(b.length<112)throw Error('잘린 GBS');format='GBS';title=str(b,16,32)||name;extra={songs:b[4],defaultSong:Math.max(0,b[5]-1)};}
 else if(magic(b,'HESM')){if(b.length<32)throw Error('잘린 HES');format='HES';extra={defaultSong:b[5],unknownSongCount:true};}
 else if(magic(b,'SNES-SPC700 Sound File Data')){if(b.length<0x10200)throw Error('잘린 SPC');format='SPC';title=str(b,0x2e,32)||name;}
 else if(magic(b,'Vgm ')){format=compressed?'VGZ':'VGM';extra=vgmCheck(b);}
 else if(magic(b,'PSF'))return {...psf(b,name),bytes:b};else if(magic(b,'pBAV'))return {format:'VAB',kind:'bank',title:name,name,bytes:b,ready:true};else throw Error('지원되는 헤더가 아닙니다. 확장자만 바꾼 파일은 읽지 않습니다.');
 return {format,kind:'gme',ready:true,title,name,bytes:b,...extra};}
function vab(data,body=null){const h=bytes(data);if(!magic(h,'pBAV')||h.length<0x20)throw Error('VAB/VH 헤더가 아닙니다.');const d=new DataView(h.buffer,h.byteOffset,h.byteLength),ver=d.getUint32(4,true),nprogram=d.getUint16(18,true),ntone=d.getUint16(20,true),nsample=d.getUint16(22,true);if(![5,6,7].includes(ver))throw Error('지원하는 VAB 버전은 5·6·7입니다.');if(nprogram>128||nsample>255)throw Error('VAB 프로그램/샘플 수가 잘못됐습니다.');const toneStart=0x820,table=toneStart+nprogram*512,headEnd=table+512;if(headEnd>h.length)throw Error('잘린 VAB/VH 속성 테이블');const audio=body?bytes(body):h.subarray(headEnd);let pos=0;const samples=[];for(let id=1;id<=nsample;id++){const size=d.getUint16(table+id*2,true)*8;if(size%16||pos+size>audio.length)throw Error('VAB 샘플 #'+id+' 크기/위치 오류. VH를 골랐다면 짝 VB도 함께 선택하세요.');samples.push({id,size,offset:pos,data:audio.subarray(pos,pos+size)});pos+=size;}
 const programs=[];let loaded=0;for(let p=0;p<128&&loaded<nprogram;p++){const nt=h[32+p*16];if(!nt)continue;if(nt>16)throw Error('한 프로그램에 16개 초과 영역은 아직 지원하지 않습니다.');const regions=[];for(let r=0;r<nt;r++){const o=toneStart+loaded*512+r*32,sample=d.getUint16(o+22,true);if(sample<1||sample>nsample)throw Error('VAB 영역의 샘플 번호가 잘못됐습니다.');regions.push({sample,root:h[o+4],fine:h[o+5],low:h[o+6],high:h[o+7],volume:h[o+2],pan:h[o+3],adsr1:d.getUint16(o+16,true),adsr2:d.getUint16(o+18,true)});}programs.push({id:p,volume:h[33+p*16],pan:h[36+p*16],regions});loaded++;}if(loaded!==nprogram)throw Error('VAB의 선언 프로그램 수와 실제 속성이 다릅니다.');return{version:ver,programs,samples,tones:ntone,warnings:['VAB는 악기 소리 묶음입니다. 곡·음표·연주 시각은 없어 채보용 곡 트랙을 생성하지 않습니다.','샘플 듣기는 44,100Hz 기준입니다. 실제 게임 재생은 해당 악기의 조율·ADSR·피치 명령에 따라 다릅니다.']};}
function decodeVag(input){const b=bytes(input);if(b.length%16||b.length>8*1024*1024)throw Error('ADPCM 샘플 크기 오류');const pcm=new Float32Array(b.length/16*28),coef=[[0,0],[60,0],[115,-52],[98,-55],[122,-60]];let s1=0,s2=0,j=0,loopStart=null,loopEnd=null;for(let off=0;off<b.length;off+=16){const shift=b[off]&15,f=b[off]>>4,flags=b[off+1];if(f>4||shift>12)throw Error('지원하지 않는 PS1 ADPCM 필터/시프트');if(flags&4)loopStart=j;for(let k=0;k<28;k++){let v=(b[off+2+(k>>1)]>>(k%2*4))&15;if(v&8)v-=16;const sample=Math.max(-32768,Math.min(32767,((v<<12)>>shift)+((s1*coef[f][0]+s2*coef[f][1]+32)>>6)));s2=s1;s1=sample;pcm[j++]=sample/32768;}if(flags&1){if(flags&2)loopEnd=j;break;}}return{pcm:pcm.subarray(0,j),sampleRate:44100,loopStart,loopEnd};}
function wavHeader(frames,rate,channels=2){if(!Number.isSafeInteger(frames)||frames<0||frames*channels*2>LIMIT.output)throw Error('WAV 크기 제한');const b=new Uint8Array(44),d=new DataView(b.buffer),write=(p,s)=>[...s].forEach((x,i)=>b[p+i]=x.charCodeAt(0));write(0,'RIFF');d.setUint32(4,36+frames*channels*2,true);write(8,'WAVEfmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,channels,true);d.setUint32(24,rate,true);d.setUint32(28,rate*channels*2,true);d.setUint16(32,channels*2,true);d.setUint16(34,16,true);write(36,'data');d.setUint32(40,frames*channels*2,true);return b;}
function monoWav(pcm,sr){const out=new Uint8Array(pcm.length*2),d=new DataView(out.buffer);for(let i=0;i<pcm.length;i++)d.setInt16(i*2,Math.round(Math.max(-1,Math.min(1,pcm[i]))*32767),true);return new Blob([wavHeader(pcm.length,sr,1),out],{type:'audio/wav'});}
function dependencies(info,files){const by=new Map();for(const f of files){const name=safePath(f.webkitRelativePath||f.name);if(by.has(name.toLowerCase()))throw Error('중복 파일 이름: '+name);by.set(name.toLowerCase(),f);}return (info.dependencies||[]).map(name=>({name,present:by.has(name.toLowerCase())}));}
const api={LIMIT,inspect,vab,decodeVag,wavHeader,monoWav,crc32,inflate,dependencies,safePath,vgmCheck};scope.PianoRetroCore=Object.freeze(api);if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
